version: '3.5'

services:
  db-orders:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: orders-service-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5555:5432'

  orders:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-service
    ports:
      - '3000:3000'
    depends_on:
      - db-orders
    volumes:
      - ./src:/store/orders/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: orders-service-db-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db-orders
